package chess;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Objects;

/**
 * Represents a single chess piece
 * <p>
 * Note: You can add to this class, but you may not alter
 * signature of the existing methods.
 */
public class ChessPiece {

    private final ChessGame.TeamColor pieceColor;
    private final ChessPiece.PieceType type;

    public ChessPiece(ChessGame.TeamColor pieceColor, ChessPiece.PieceType type) {
        this.pieceColor = pieceColor;
        this.type = type;
    }

    /**
     * The various different chess piece options
     */
    public enum PieceType {
        KING,
        QUEEN,
        BISHOP,
        KNIGHT,
        ROOK,
        PAWN
    }

    /**
     * @return Which team this chess piece belongs to
     */
    public ChessGame.TeamColor getTeamColor() {
        return pieceColor;
    }

    /**
     * @return which type of chess piece this piece is
     */
    public PieceType getPieceType() {
        return type;
    }

    /**
     * Calculates all the positions a chess piece can move to
     * Does not take into account moves that are illegal due to leaving the king in
     * danger
     *
     * @return Collection of valid moves
     */
    public Collection<ChessMove> pieceMoves(ChessBoard board, ChessPosition myPosition) {
        ChessPiece piece = board.getPiece(myPosition);
        switch(piece.getPieceType()) {
            case PieceType.BISHOP:
                return bishopMoves(board, myPosition, piece);
            case PieceType.KING:
                return kingMoves(board, myPosition, piece);
            case PieceType.KNIGHT:
                return knightMoves(board, myPosition, piece);
            case PieceType.PAWN:
                return pawnMoves(board, myPosition, piece);
            case PieceType.QUEEN:
                return queenMoves(board, myPosition, piece);
            case PieceType.ROOK:
                return rookMoves(board, myPosition, piece);
            default:
                return null;
        }
    }

    private static ArrayList<ChessMove> bishopMoves(ChessBoard board, ChessPosition startPosition, ChessPiece piece) {
        ArrayList<ChessMove> validMoves = new ArrayList<>();

        return validMoves;
    }

    private static ArrayList<ChessMove> kingMoves(ChessBoard board, ChessPosition startPosition, ChessPiece piece) {
        ArrayList<ChessMove> validMoves = new ArrayList<>();

        return validMoves;
    }

    private static ArrayList<ChessMove> knightMoves(ChessBoard board, ChessPosition startPosition, ChessPiece piece) {
        ArrayList<ChessMove> validMoves = new ArrayList<>();

        return validMoves;
    }

    private static ArrayList<ChessMove> pawnMoves(ChessBoard board, ChessPosition startPosition, ChessPiece piece) {
        ArrayList<ChessMove> validMoves = new ArrayList<>();

        return validMoves;
    }

    private static ArrayList<ChessMove> queenMoves(ChessBoard board, ChessPosition startPosition, ChessPiece piece) {
        ArrayList<ChessMove> validMoves = new ArrayList<>();

        return validMoves;
    }

    private static ArrayList<ChessMove> rookMoves(ChessBoard board, ChessPosition startPosition, ChessPiece piece) {
        ArrayList<ChessMove> validMoves = new ArrayList<>();

        return validMoves;
    }


    // Created by IntelliJ
    @Override
    public boolean equals(Object o) {
        if (!(o instanceof ChessPiece piece)) {
            return false;
        }
        return pieceColor == piece.pieceColor && type == piece.type;
    }

    // Created by IntelliJ
    @Override
    public int hashCode() {
        return Objects.hash(pieceColor, type);
    }

    // Structure generated by IntelliJ
    @Override
    public String toString() {
        return "{" + pieceColor + "," + type + "}";
    }
}
